#region AgileEAS.NET-generated
//------------------------------------------------------------------------------
//     AgileEAS.NET应用开发平台，是基于敏捷并行开发思想以及.NET构件技术而开发的一个应用系统快速开发平台，用于帮助中小软件企业
//建立一条适合快速变化的开发团队，以达到节省开发成本、缩短开发时间，快速适应市场变化的目的。
//     AgileEAS.NET应用开发平台包含基础类库、资源管理平台、运行容器、开发辅助工具等四大部分，资源管理平台为敏捷并行开发提供了
//设计、实现、测试等开发过程的并行，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子
//功能模块按照业务功能组织成单独的程序集文件，各子系统开发完成后，由AgileEAS.NET资源管理平台进行统一的集成部署。
//
//     AgileEAS.NET SOA 中间件平台是一套免费的快速开发工具，可以不受限制的用于各种非商业开发之中，商业应用请向作者获取商业授权，
//商业授权也是免费的，但是对于非授权的商业应用视为侵权，开发人员可以参考官方网站和博客园等专业网站获取公开的技术资料，也可以向
//AgileEAS.NET官方团队请求技术支持。
//
// 官方网站：http://www.smarteas.net
// 团队网站：http://www.agilelab.cn
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由AgileEAS.NET数据模型设计工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.ComponentModel;
using System.Data;
using EAS.Data;
using EAS.Data.Access;
using EAS.Data.ORM;
using EAS.Data.Linq;

namespace Northwind.Entities
{
   /// <summary>
   /// 实体对象 Product(产品字典)。
   /// </summary>
   [Serializable()]
   [Table("Products","产品字典")]
   partial class Product: DataEntity<Product>, IDataEntity<Product>
   {
       public Product()
       {
       }
       
       protected Product(SerializationInfo info, StreamingContext context)
           : base(info, context)
       {
       }
       
       #region O/R映射成员

       /// <summary>
       /// 产品ID 。
       /// </summary>
       [Column("ProductID","产品ID"),PrimaryKey,NotNull]
       [DisplayName("产品ID")]
       public int ProductID
       {
           get;
           set;
       }

       /// <summary>
       /// 产品名称 。
       /// </summary>
       [Column("ProductName","产品名称"),DataSize(128),NotNull]
       [DisplayName("产品名称")]
       public string ProductName
       {
           get;
           set;
       }

       /// <summary>
       /// 产品种类ID 。
       /// </summary>
       [Column("CategoryID","产品种类ID"),NotNull]
       [DisplayName("产品种类ID")]
       public int CategoryID
       {
           get;
           set;
       }

       /// <summary>
       /// 规格 。
       /// </summary>
       [Column("Spec","规格"),DataSize(128)]
       [DisplayName("规格")]
       public string Spec
       {
           get;
           set;
       }

       /// <summary>
       /// 单位 。
       /// </summary>
       [Column("Unit","单位"),DataSize(128)]
       [DisplayName("单位")]
       public string Unit
       {
           get;
           set;
       }

       /// <summary>
       /// 价格 。
       /// </summary>
       [Column("UnitPrice","价格"),DataSize(18,4),NotNull]
       [DisplayName("价格")]
       public decimal UnitPrice
       {
           get;
           set;
       }

       /// <summary>
       /// 输入码 。
       /// </summary>
       [Column("InputCode","输入码"),DataSize(32)]
       [DisplayName("输入码")]
       public string InputCode
       {
           get;
           set;
       }

       /// <summary>
       /// 最后更新时间 。
       /// </summary>
       [Column("LMTime","最后更新时间"),NotNull,CacheUpdated]
       [DisplayName("最后更新时间")]
       public DateTime LMTime
       {
           get;
           set;
       }
       
       #endregion
       
       #region O/R引用实体

       [NonSerialized]
       private Category m_Category;

       /// <summary>
       /// 产品种类 。
       /// </summary>
       [XmlIgnore]
       [RefEntity("CategoryID", "产品种类", typeof(Category), "CategoryID", false, true)]
       public Category Category
       {
           get
           {
               if ((this.m_Category == null && ! object.Equals(this.CategoryID, null)) || (this.m_Category!=null && this.m_Category.CategoryID != this.CategoryID))
               {
                   this.m_Category = Category.LazyCache(this.CategoryID);
               }

               return this.m_Category;
           }
           set
           {
               this.m_Category = value;
           }
       }
       
       #endregion
       
       #region O/R子实体
       
       #endregion
   }
}
